[tool.poetry]
name = "pornLib"
version = "1.0.0"
description = "Get videos from porn sites"
authors = ["sofiagros"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sofia-gros/porn-lib-python"